### PR TITLE
Tic Tac Toe Milestone 3: Game Logic

### PR DESCRIPTION
**Pull request by Janluc**
## Game Logic

- Created separate files for classes
- Error handling for various types of malicious player input
- Implement Game loop and set win and draw conditions

### CODE REVIEW

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle: :stop_sign: 
Hello team!
I'd like to review your code but I think you've made a mistake in your folder structure and right now it's impossible to run your game. Your main.rb is asking for player.rb and gamemanager.rb from the lib folder but in that folder, there are no files with those names. I think you've deleted them by mistake.

Kindly add those files to the lib folder and submit for a re-review. :smile_cat: 
If you have any questions about the review, feel free to reach me via slack.
Eyüp Sercan UYGUR

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes  ♲
Hi @Janluc and @che30, 👏 You did very well on this project. ✨ I applaud you for the intuitive UX. Most requirements have done 👌, Kindly fix the following issues.

[REQUIRED]

- Remove inline comments
- Your project breaks with the error message of , `cannot load such file -- ../lib/player.rb (LoadError)`. Use `require_relative` for files in your directory instead of require/load is a ruby convention.

[Optional]

We favor the division of code in many methods. (This makes debugging easier and the code more readable). This applies to functions too.

Once you fix the issues, kindly submit another code review. ♲

 Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/)

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Change Required :vertical_traffic_light: :warning: 
## Hello @Janluc and @che30  :handshake: :handshake: :handshake: 
:+1: This is so impressive. You have done a splendid job implementing an outstanding game logic, congratulations guys and keep it up :muscle: :muscle:
### :warning: However we need to fix one mandatory and some optional issue(s) to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
## Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] Please refactor the `.rubocop.yml` file to use [this one](https://raw.githubusercontent.com/microverseinc/linters-config/master/ruby/.rubocop.yml) from microverse guidelines, => I used it to lint your project, and found three offenses
- [x] I played your game and when it asked me to play again, when I pressed any other key (other than Y) it continued as if I pressed Y, => is that normal? If so, then you should explain to players. Like this: Press any key for Y or N to terminate the game. Try something like that.

# [Optional changes] :yellow_circle: 
- [ ] When the game asked me to choose Heads Or Tail, I pressed any other key (other than H or T) it continued as if I pressed H or T, => is that normal? If so, could you explain that to players? Like this: Press any key for H or just press enter for T
- [ ] in the `bin/main.rb` file, there are a lot of codes and logic which aren't in any method, for the sake of code maintenability, readability and debugging I would advise you to use classes, and methods more often. Instead of leaving your logic out like that.

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)
_slack:_ `@Mugirase Emmanuel` | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

**Review by Georjane — APPROVED** [review]
## Status: PR Approved ✔️
Hi @Janluc and @che30 🙌

Congratulations on successfully completing this milestone! 🎊🎊🎊
Your work is pretty amazing. I love the implementation of the coin toast and the ability of a player to choose a symbol to play with. 👏👏
You guys have corrected all changes required by the previous TSE and so you can go ahead and merge this PR. 👍

Goodluck on your next project and Happy coding 💻

**Pull request merged**
